const TYPE_LABELS = { competition: "比赛", lecture: "讲座", salon: "沙龙", exhibition: "展览", volunteer: "志愿", part_time: "兼职", internship: "实习", workshop: "工作坊", online: "线上活动" };
const ICONS = { competition: "◒", lecture: "✦", salon: "☕", exhibition: "◌", volunteer: "✋", part_time: "↗", internship: "▦", workshop: "⌁", online: "◎" };
const COVERS = { competition: "competition", lecture: "lecture", salon: "salon", exhibition: "exhibition", volunteer: "volunteer", part_time: "part-time", internship: "internship", workshop: "workshop", online: "online" };
const state = { items: [], filtered: [] };
const $ = (selector) => document.querySelector(selector);
function formatDate(value) { if (!value) return "时间待定"; return new Intl.DateTimeFormat("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value * 1000)); }
function category(item) { if (item.type === "lecture") return "lecture"; if (item.type === "competition") return "competition"; if (item.type === "exhibition") return "exhibition"; if (item.type === "volunteer") return "volunteer"; if (item.type === "salon") return "salon"; return "default"; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"']/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "\"":"&quot;", "'":"&#39;" }[char])); }
function applyFilters() { const query = $("#query").value.trim().toLowerCase(); const type = $("#type").value; const timing = $("#timing").value; const fee = $("#fee").value; const now = Math.floor(Date.now() / 1000); const limit = timing === "week" ? now + 7 * 86400 : timing === "month" ? now + 30 * 86400 : timing === "upcoming" ? now + 365 * 86400 : Infinity; state.filtered = state.items.filter((item) => { const haystack = `${item.title} ${item.description} ${item.organizer ?? ""} ${item.venueName ?? ""} ${(item.tags ?? []).join(" ")}`.toLowerCase(); return (!query || haystack.includes(query)) && (type === "all" || item.type === type) && (fee === "all" || item.feeType === fee) && (!item.startsAt || (item.startsAt >= now && item.startsAt <= limit)); }); render(); }
function render() { $("#count").textContent = `${state.filtered.length} 个公开机会`; $("#empty").hidden = state.filtered.length > 0; $("#list").innerHTML = state.filtered.map((item) => { const type = category(item); const cover = COVERS[item.type] ?? "online"; const tags = [TYPE_LABELS[item.type] ?? "其他", ...(item.tags ?? [])].slice(0, 3); const venue = item.isOnline ? "线上活动" : (item.venueName || item.city || "地点待定"); const link = item.sourceUrl || item.registrationUrl; return `<article class="activity-card"><div class="activity-banner ${type}"><img class="activity-cover" src="covers/${cover}.png" alt="" loading="lazy" /><div class="cover-scrim" aria-hidden="true"></div><span class="banner-icon">${ICONS[item.type] ?? "✦"}</span><span class="banner-name">${escapeHtml(TYPE_LABELS[item.type] ?? "其他活动")}</span></div><div class="activity-content"><h3 class="activity-title">${escapeHtml(item.title)}</h3><div class="tags">${tags.map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div><div class="meta"><span>⌖ ${escapeHtml(venue)}</span><span>◷ ${formatDate(item.startsAt)}</span></div><div class="card-footer"><span>${escapeHtml(item.sourceName || "公开来源")}</span>${link ? `<a href="${escapeHtml(link)}" target="_blank" rel="noreferrer">查看原文 ↗</a>` : ""}</div></div></article>`; }).join(""); }
async function boot() { try { const response = await fetch("data/opportunities.json", { cache: "no-store" }); if (!response.ok) throw new Error("snapshot unavailable"); const snapshot = await response.json(); state.items = snapshot.items ?? []; $("#sync-time").textContent = snapshot.generatedAt ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(snapshot.generatedAt)) : "待同步"; $("#sync-status").textContent = snapshot.statusMessage || "公开快照"; const types = [...new Set(state.items.map((item) => item.type))]; $("#type").insertAdjacentHTML("beforeend", types.map((type) => `<option value="${escapeHtml(type)}">${escapeHtml(TYPE_LABELS[type] ?? type)}</option>`).join("")); applyFilters(); } catch { $("#sync-time").textContent = "暂时不可用"; $("#sync-status").textContent = "请稍后刷新"; $("#count").textContent = "活动数据暂不可用"; } }
["query", "type", "timing", "fee"].forEach((id) => document.getElementById(id).addEventListener(id === "query" ? "input" : "change", applyFilters));
boot();
